\ProvidesClass{resume2}[ownedcv]
\LoadClass[11pt, a4paper]{article}

\usepackage[left=0.5in, top=0.5in, right=0.5in, bottom=0.5in]{geometry} % Márgenes de página
\usepackage[utf8]{inputenc} % Compatibilidad de texto entre OS
\usepackage[T1]{fontenc} % Fuente de códigos
\usepackage[spanish]{babel} % Compatibilidad de idioma
\usepackage{lipsum} % Texto de relleno
\usepackage{amsmath} % Operaciones matemáticas complejas
\usepackage{amsfonts} % Tipografía matemática
\usepackage{amssymb} % Tipografía matemática
\usepackage{amsthm} % Tipografía de teoremas
\usepackage{tikz} % Creación de gráficos
\usepackage{float} % Posicionamiento de flotantes
\usepackage{graphicx} % Manejo de imágenes de bits
\usepackage{xcolor} % Personalización de colores
\usepackage{fontawesome} % Íconos
\usepackage[hidelinks]{hyperref} % Hiperreferencias
\usepackage{multicol} % Uso de múltiples columnas
\usepackage{float} % Posicionamiento exacto de flotantes
\pagestyle{empty} % Eliminar numeración de páginas
\hypersetup{
	colorlinks=false,
	linkcolor=blue,
	filecolor=magenta,      
	urlcolor=blue,
}
%\usepackage[parfill]{parskip} % Remove paragraph indentation
%\usepackage{array} % Required for boldface (\bf and \bfseries) tabular columns
%\usepackage{ifthen} % Required for ifthenelse statements
%\usepackage{latexsym}
%\usepackage[empty]{fullpage}
%\usepackage{titlesec}
%\usepackage{marvosym}
%\usepackage[usenames,dvipsnames]{color}
%\usepackage{verbatim}
%\usepackage{enumitem}
%\usepackage{fancyhdr}
%\usepackage{tabularx}


\definecolor{vino}{HTML}{9A2A2A}
\definecolor{rojo}{RGB}{158,0,79} %HTML
\definecolor{marron}{RGB}{195,112,14}
\definecolor{naranja}{RGB}{225,168,0}
\definecolor{amarillo}{RGB}{255,200,0}
\definecolor{plomo}{RGB}{134,133,137}

